### PR TITLE
Refresh the Dashboards

### PR DESCRIPTION
**Pull request by stephenyeargin**
The styles on the dashboards around the office have been a bit off. This makes them more consistent and fixes a bunch of styling issues. See the `.app-env-dist` file for a list of the new keys for the weather widget as well as a change for the Nextbus integration.

- Adds weather widget
- Changes the Twitter search to be configurable via environment variable
- Swaps up a logo blatantly stolen from [here](https://github.com/tabatkins/bikeshed)
- Updates the Nextbus integration to search all stops near the latitude/longitude of the office

screen shot 2015-05-29 at 11 44 29 pm
screen shot 2015-05-29 at 11 44 39 pm
screen shot 2015-05-29 at 11 45 08 pm
screen shot 2015-05-31 at 4 19 01 pm
screen shot 2015-05-29 at 11 57 39 pm

---

## New / Replacement Environment Variables

```
# Weather
export WEATHER_OBSERVATION_STATION=2457170
export WEATHER_OBSERVATION_UNIT=F
```

```
# Twitter
[...]
export TWITTER_SEARCH_TERM="#github"
```

```
# Nextbus
[...]
export NEXTBUS_LATLON=36.162876,-86.78136
```
(Replaces the station identifier list)

### CODE REVIEW

**Comment by jameswhite** [comment]
I think @rick and I actually like the github twitter search. It sometimes shows some crazy stuff. The 1400x900 boards need to be broken up into 2 separate boards now.

**Comment by jameswhite** [comment]
But this PR is :+1:  to merge for sure. These look amazing. Was the "Bikeshed wall blue" a conscious color choice, or just a fortunate accident?

**Comment by stephenyeargin** [comment]
Yes.

**Comment by stephenyeargin** [comment]
Updated the description. The :fire::chicken: thing was actually a side effect of it moving into a config variable.

**Comment by stephenyeargin** [comment]
[x] Split the 1400 board up. Can't remember where everything lives, but this gets it there.

**Comment by jameswhite** [comment]
You might name then 1440x900+0+0-left and 1440x900+0+0-right instead of 1440x900+0+1, that's the resolution and x,y offset. wxh+x+y. Those are the two over the kegerator and I can make them pick the correct one.

**Comment by stephenyeargin** [comment]
:cool: Done

**Comment by jameswhite** [comment]
:shipit:

**Pull request merged**
