### PR TITLE
just a spike

### PR DESCRIPTION
**Pull request by jameswhite**
I'll need to embetter this layout.

### CODE REVIEW

**Comment by stephenyeargin** [comment]
interesting. if it works, gopher it. :+1:

**Comment by jameswhite** [comment]
It's going to look terrible, I just cloned the old monitor config (which was a different resolution.)

**Comment by stephenyeargin** [comment]
Make it serviceable, and I'll fix it later (because it'll piss me off). :sparkles:

**Comment by jameswhite** [comment]
It's mounted and running now.
img_3939

**Comment by stephenyeargin** [comment]
*twitches*

**Comment by jameswhite** [comment]
https://dashboard.thebikeshed.io/1280x1024+0+0

**Comment by jameswhite** [comment]
nevermind the routing on that may be broken

**Comment by jameswhite** [comment]
@stephenyeargin feel free to step on this branch if you want.

**Comment by stephenyeargin** [comment]
9f945ed

screen shot 2015-12-24 at 10 32 31 am

**Comment by jameswhite** [comment]
@stephenyeargin https://www.youtube.com/watch?v=vFUJrg5GAvs&t=2m24s

**Comment by jameswhite** [comment]
img_3998

**Comment by stephenyeargin** [comment]
Looks like it could use another 10-20 pixels added to the base widget height to fill out the space at the bottom.

**Comment by stephenyeargin** [comment]
shipit

**Pull request merged**
