### PR TITLE
Add ENBW menu widget

### PR DESCRIPTION
**Pull request by bval**
image 2017-10-12 at 4 22 39 pm

I haven't added this to any dashboard layouts yet. Open to suggestions on where it goes. You can add it in for local testing with:

```
    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="enbw" data-view="Enbw" data-title="On Tap at ENBW" ></div>
    </li>
```

### CODE REVIEW

**Comment by rimboy** [comment]
Hell yeah! We may want to adapt this so we can serve it on our website.

Sean

**Comment by stephenyeargin** [comment]
@rimboy Data retrieval example:

```
curl -H "Accept: application/json" http://enbw.herokuapp.com
```

**Comment by rick** [comment]
```
curl -H "Accept: application/json" http://enbw.herokuapp.com | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3314    0  3314    0     0  35702      0 --:--:-- --:--:-- --:--:-- 36021
```

```json
{
  "beers": [
    {
      "id": 1,
      "name": "Miro Miel",
      "tag_line": "Blonde Ale with Local Honey",
      "image": "http://www.eastnashbeerworks.com/_assets/img/beers/Miro-01.png",
      "abv": "5.2",
      "tier_id": 1,
      "position": 1,
      "created_at": "2017-03-26T16:49:04.698Z",
      "updated_at": "2017-10-04T19:56:10.219Z",
      "active": true
    },
    {
      "id": 2,
      "name": "Cumberland Punch",
      "tag_line": "American Wheat Ale",
      "image": "http://www.eastnashbeerworks.com/_assets/img/beers/Cumberland-01.png",
      "abv": "6.2",
      "tier_id": 1,
      "position": 2,
      "created_at": "2017-03-26T16:49:29.804Z",
      "updated_at": "2017-07-29T02:37:43.136Z",
      "active": true
    },
    {
      "id": 4,
      "name": "Roaming Dog",
      "tag_line": "ESB + APA = ASB",
      "image": "https://s3.amazonaws.com/enbw-assets/Roaming+Dog+.png",
      "abv": "5.2",
      "tier_id": 1,
      "position": 4,
      "created_at": "2017-03-26T16:51:15.504Z",
      "updated_at": "2017-06-23T20:07:34.493Z",
      "active": true
    },
    {
      "id": 19,
      "name": "I Am An IPA Agent!",
      "tag_line": "Swayzest Centennial APA",
      "image": "http://www.eastnashbeerworks.com/_assets/img/global/logo.svg",
      "abv": "5.0",
      "tier_id": 1,
      "position": 5,
      "created_at": "2017-08-23T23:38:23.539Z",
      "updated_at": "2017-08-23T23:38:23.539Z",
      "active": true
    },
    {
      "id": 5,
      "name": "Swing Bridge IPA",
      "tag_line": "American IPA",
      "image": "http://www.eastnashbeerworks.com/_assets/img/beers/SwingBridge-01.png",
      "abv": "6.5",
      "tier_id": 2,
      "position": 5,
      "created_at": "2017-03-26T16:51:34.285Z",
      "updated_at": "2017-09-12T21:42:48.897Z",
      "active": true
    },
    {
      "id": 13,
      "name": "Hipster Dance Party",
      "tag_line": "Double IPA  $3 Taster / $5 Half Pint",
      "image": "https://s3.amazonaws.com/enbw-assets/Hipster+Dance+Party.png",
      "abv": "8.5",
      "tier_id": 3,
      "position": 8,
      "created_at": "2017-05-04T23:02:32.572Z",
      "updated_at": "2017-06-15T13:58:08.809Z",
      "active": true
    },
    {
      "id": 16,
      "name": "Augustfest",
      "tag_line": "Wheat ale w/ blackberries",
      "image": "http://www.eastnashbeerworks.com/_assets/img/global/logo.svg",
      "abv": "4.5",
      "tier_id": 1,
      "position": 9,
      "created_at": "2017-08-05T00:46:52.805Z",
      "updated_at": "2017-09-02T00:47:21.751Z",
      "active": true
    },
    {
      "id": 17,
      "name": "Coconut Cream Pie",
      "tag_line": "Ale with coconut and lactose",
      "image": "http://www.eastnashbeerworks.com/_assets/img/global/logo.svg",
      "abv": "6.7",
      "tier_id": 2,
      "position": 9,
      "created_at": "2017-08-11T14:12:54.627Z",
      "updated_at": "2017-08-11T22:48:45.539Z",
      "active": true
    },
    {
      "id": 10,
      "name": "Shelby Bottoms Brown",
      "tag_line": "Hickory Smoked Brown",
      "image": "http://www.eastnashbeerworks.com/_assets/img/global/logo.svg",
      "abv": "4.5",
      "tier_id": 1,
      "position": 10,
      "created_at": "2017-03-26T16:54:57.725Z",
      "updated_at": "2017-05-04T23:53:08.230Z",
      "active": true
    },
    {
      "id": 15,
      "name": "Woodland St. Azacca",
      "tag_line": "Session IPA Azacca hops",
      "image": "http://www.eastnashbeerworks.com/_assets/img/beers/WoodlandSt-01.png",
      "abv": "4.5",
      "tier_id": 1,
      "position": null,
      "created_at": "2017-07-06T19:59:35.575Z",
      "updated_at": "2017-08-31T20:24:16.267Z",
      "active": true
    }
  ],
  "tiers": [
    {
      "id": 1,
      "name": "Tier 1",
      "taster": 2,
      "half_pint": 3,
      "pint": 5,
      "crowler": 8,
      "growler": 13,
      "created_at": "2017-03-26T16:47:21.704Z",
      "updated_at": "2017-05-05T00:55:15.283Z",
      "short_hand": "1",
      "hide": false
    },
    {
      "id": 2,
      "name": "Tier 2",
      "taster": 3,
      "half_pint": 4,
      "pint": 6,
      "crowler": 10,
      "growler": 16,
      "created_at": "2017-03-26T16:47:42.640Z",
      "updated_at": "2017-05-05T00:55:15.276Z",
      "short_hand": "2",
      "hide": false
    }
  ],
  "guest_beers": [
    {
      "id": 1,
      "name": "Jack's Hard Cider",
      "price": 5,
      "created_at": "2017-03-26T16:48:06.056Z",
      "updated_at": "2017-03-26T16:48:06.056Z"
    }
  ]
}
```

**Comment by bval** [comment]
[See also.](https://github.com/RJFryman/enbw/pull/1)

giphy 4

**Comment by stephenyeargin** [comment]
Merging this, will start fixing layouts in a later PR (lots to add/delete)

**Pull request merged**
